name: Build

on: [push, pull_request]

jobs:

  generate-matrix:
    name: Generate matrix for build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
          sudo luet install utils/jq
      - name: Set matrix for build
        id: set-matrix
        run: |
          JSON="{\"include\":"
          JSONline="$(luet tree pkglist --tree packages -o json | jq -rc '.packages')"
          JSON="$JSON$JSONline"
          JSON="$JSON}"
          # Set output
          echo "::set-output name=matrix::$( echo "$JSON" )"

  build:
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release space from worker
      run: |
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
    - run: |
        git fetch --prune --unshallow
    # CONFIGURE: we might use quay here in our example, adapt as needed
    # - name: Login to Quay Registry
    #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #   run: echo ${{ secrets.QUAY_ROBOT_PASSWORD }} | docker login -u ${{ secrets.QUAY_ROBOT_USERNAME }} --password-stdin quay.io

    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}      
    - name: Build 🔧
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
      with:
        # tree: packages
        build: true
        onlyMissing: true
        FINAL_REPO: ghcr.io/${{ github.repository }}
        pushCache: false
        CURRENT_PACKAGE:  ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
    - name: Build 🔧
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        # tree: packages
        build: true
        FINAL_REPO: ghcr.io/${{ github.repository }}
        onlyMissing: true
        pushCache: true
        CURRENT_PACKAGE:  ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
        # Repository used to pull images from. needed if you list any repo in .luet.yaml
      #PULL_REPOSITORY: quay.io/mocaccinocache/desktop
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.category }}-${{ matrix.name }}-${{ matrix.version }}.zip
        path: |
          build/

  create-repo:
    needs: build
    env:
      FINAL_REPO: ghcr.io/${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    # - name: Login to Quay Registry
    #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #   run: echo ${{ secrets.QUAY_ROBOT_PASSWORD }} | docker login -u ${{ secrets.QUAY_ROBOT_USERNAME }} --password-stdin quay.io
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}    

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - name: Merge artifacts 🔧
      run: |
        mkdir build || true
        for i in $(ls | grep zip); do
          cp -rfv $i/* build
        done
        ls -liah
        ls -liah build

    - name: Download meta
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
      with:
        # tree: packages
        downloadMeta: true
        FINAL_REPO: ghcr.io/${{ github.repository }}
        REPOSITORY_TYPE: docker

    - name: Create repo 🔧
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
      with:
        # tree: packages
        createRepo: true
        pushCache: true
        FINAL_REPO: ghcr.io/${{ github.repository }}
        REPOSITORY_TYPE: docker

    # - name: Deploy GH Pages 🚀
    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    #   uses: JamesIves/github-pages-deploy-action@3.6.2
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     BRANCH: gh-pages # The branch the action should deploy to.
    #     FOLDER: build # The folder the action should deploy.
    #     CLEAN: true # Automatically remove deleted files from the deploy branch
    #     SINGLE_COMMIT: true